#!/bin/bash

INPUT1=$1
INPUT2=$2
THRESH=$3
OUTPUT=$4

if [ $# -lt 4 ]; then
    echo "overlap <input1> <input2> <thresh> <output> "; exit 0;
fi

tmp1="$(mktemp --suffix .nii.gz)"
tmp2="$(mktemp --suffix .nii.gz)"

mri_binarize --i $INPUT1 --min $THRESH --o $tmp1
mri_binarize --i $INPUT2 --min $THRESH --o $tmp2

fscalc $tmp2 mul 2 add $tmp1 --o $OUTPUT

